name: deploy-to-ghpages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install packages
        run: npm i
      - name: Build
        run: npm run build
      - name: set up gh-pages workspace
        run: cd dist && git init && git branch -M gh-pages && git remote add origin https://github.com/AVOCAT-team/anticat-site.git
      - name: deploying to gh-pages
        run: git add . && git commit -m "deploy" && git push origin gh-pages --force
