name: deploy-to-ghpages

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Npm building
        run: npm run build
      - run: cd dist
      - name: set up gh-pages workspace
        run: git init && git branch -M gh-pages && git remote add origin https://github.com/AVOCAT-team/anticat-site.git 
      - name: deploying to gh-pages
        run: git add . && git commit -m "deploy" && git push origin gh-pages
